language: nix
branches:
  only:
  - sources
notifications:
  email:
  - false

script:
- nix-shell --pure --run 'make DST=docs deploy'

deploy:
  local-dir: docs
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  target-branch: master
  on:
    branch: sources

